Repository Financial-Times/o-header, pull requests merged in 2020-09, with the labels that each got.

#395 Add support for right aligned subnav items.
  demos/src/subnav-right-align.json
  demos/src/subnav.mustache
  origami.json
  src/scss/features/_subnav.scss
Labels: component, release:minor

#397 update to latest eslint origami component config
  package.json
Labels: component

#406 Include the link text in the current page label.
  demos/src/grid-demo.mustache
  demos/src/header.mustache
  demos/src/mega-menu.mustache
  demos/src/pa11y.mustache
  demos/src/simple-header.mustache
  demos/src/sticky-header.mustache
  demos/src/subbrand.mustache
  demos/src/subnav.mustache
  demos/src/transparent-header.mustache
Labels: component

#404 Do not output malformed modifier class in demos given no link variant.
  demos/src/grid-demo.mustache
  demos/src/header.mustache
  demos/src/pa11y.mustache
  demos/src/simple-header.mustache
  demos/src/sticky-header.mustache
  demos/src/subbrand.mustache
  demos/src/transparent-header.mustache
Labels: component

#405 Correct core and enhanced experiences in local demos.
  README.md
  demos/src/main.js
  demos/src/main.scss
Labels: component

#409 Update drawer search sort order.
  demos/src/deprecated-markup.mustache
  demos/src/grid-demo.mustache
  demos/src/header.mustache
  demos/src/pa11y.mustache
  demos/src/simple-header.mustache
  demos/src/sticky-header.mustache
  demos/src/subbrand.mustache
  demos/src/transparent-header.mustache
  origami.json
  src/scss/features/_drawer.scss
Labels: component

#410 Do not use the `order` property to arrange the drawer.
  src/scss/features/_drawer.scss
Labels: component

#411 Normalise drawer search input style
  src/scss/features/_drawer.scss
  src/scss/features/_search.scss
Labels: component, release:patch

#412 Fix transparent variant regression and document limitations.
  README.md
  demos/src/deprecated-markup.mustache
  demos/src/grid-demo.mustache
  demos/src/header.json
  demos/src/header.mustache
  demos/src/mega-menu.json
  demos/src/pa11y.mustache
  demos/src/simple-header.mustache
  demos/src/sticky-header.mustache
  demos/src/subbrand.json
  demos/src/subbrand.mustache
  demos/src/subnav-right-align.json
  demos/src/subnav.json
  demos/src/transparent-header.json
  demos/src/transparent-header.mustache
  origami.json
  src/scss/_brand.scss
  src/scss/features/_transparent.scss
Labels: component, release:patch
